AqualehaTwigBundle:
    resource: "@AqualehaTwigBundle/Controller/"
    type:     annotation
    prefix:   /

AqualehaAppBundle:
    resource: "@AqualehaAppBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
