source 'http://rubygems.org'

gem 'capistrano', '~> 3.1.0'
gem 'capistrano-rails', '~> 1.1.0'
gem 'capistrano-composer'
gem 'capistrano-symfony', '~> 1.0.0.rc1'
# integrate bundler with capistrano
gem 'capistrano-bundler'

# if you are using RBENV
gem 'capistrano-rbenv', "~> 2.0" 
# Use the Unicorn app server
gem 'unicorn'
gem 'rake', "~> 11.1.2"
gem 'net-ssh', "~> 3.1.1"

